# -*- coding: utf-8 -*-
"""minishell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fSSUxJxrfO_dm-5ybylEweNHMia6xv_
"""

#!/usr/bin/env python3

import os
import shlex
import signal
import sys

# Estructura de datos para rastrear procesos hijos en segundo plano
# Evita que se queden como procesos "zombie" (procesos que terminaron pero siguen en la tabla)
background_pids = set()


def sigchld_handler(signum, frame):
    """
    MANEJO DE SEÑALES (SIGCHLD): El kernel envía esta señal al padre cuando un hijo termina.
    Limpia procesos en segundo plano de forma asíncrona.
    """
    try:
        while True:
            # os.WNOHANG: Retorna inmediatamente si ningún hijo ha cambiado de estado.
            # Esto evita que el shell se congele esperando a que un proceso termine.
            pid, status = os.waitpid(-1, os.WNOHANG)

            # Si pid es 0, no hay más hijos que hayan terminado en este momento
            if pid == 0:
                break

            if pid in background_pids:
                background_pids.remove(pid)

                # Interpretación del estado de salida
                if os.WIFEXITED(status):
                    code = os.WEXITSTATUS(status)
                    print(f"\nProceso {pid} terminó (código {code})")

                elif os.WIFSIGNALED(status):
                    sig = os.WTERMSIG(status)
                    print(f"\nProceso {pid} terminó por señal {sig}")

    except ChildProcessError:
        pass


def ignore_sigint(signum, frame):
    "Evita que el shell se cierre con Ctrl+C. Simplemente imprime una nueva línea."
    print()


def parse_command(line):
    "Tokeniza la entrada y detecta el símbolo '&' para segundo plano"
    "Divide la cadena respetando comillas"

    try:
        args = shlex.split(line)
    except ValueError:
        print("Error al leer el comando")
        return None, False

    if not args:
        return None, False

    background = False
    # Detectar el operador '&' al final para ejecución asíncrona
    if args[-1] == "&":
        background = True
        args = args[:-1]

    return args, background


def run_command(args, background):
    """
    EL CICLO FORK-EXEC:
    1. fork(): Crea una copia del proceso.
    2. execvp(): El hijo reemplaza su memoria con el nuevo binario.
    3. waitpid(): El padre espera (si es primer plano).
    """

    try:
        # Al llamar a fork, el SO duplica el shell.
        # Ahora hay dos procesos ejecutando la siguiente línea.
        pid = os.fork()

    except OSError as e:
        print("No se pudo crear el proceso:", e)
        return

    if pid == 0:
        # --- BLOQUE DEL HIJO ---
        # Restauramos SIGINT para que el comando (ej: 'top' o 'sleep')
        # sí responda a Ctrl+C y pueda ser interrumpido por el usuario.

        signal.signal(signal.SIGINT, signal.SIG_DFL)

        try:
            # execvp busca el comando en el PATH automáticamente.
            # No retorna si tiene éxito; el proceso hijo "muere" para convertirse en el nuevo programa.
            os.execvp(args[0], args)

        except FileNotFoundError:
            os.write(2, f"Comando no encontrado: {args[0]}\n".encode())

        except Exception as e:
            os.write(2, f"Error al ejecutar: {e}\n".encode())

        #Si llegó aquí, execvp falló. Termina el proceso hijo inmediatamente.
        os._exit(1)

    else:
        # --- BLOQUE DEL PADRE ---
        if background:
            # En segundo plano, se guarda el PID y se siguen pidiendo comandos
            background_pids.add(pid)
            print(f"Proceso en segundo plano: {pid}")

        else:
            # En primer plano, el shell se bloquea hasta que el hijo termine
            while True:
                try:
                    os.waitpid(pid, 0)
                    break
                except InterruptedError:
                    # Si el wait es interrumpido por una señal (como SIGCHLD), reintentamos
                    continue


def main():
  # Configurar señales iniciales
    signal.signal(signal.SIGCHLD, sigchld_handler)
    signal.signal(signal.SIGINT, ignore_sigint)

    while True:

        try:
            line = input("minishell> ")

        except EOFError:
            print()
            break

        except KeyboardInterrupt:  # Maneja Ctrl+C durante el input
            print()
            continue

        line = line.strip()

        if not line:
            continue

        if line == "exit":
            break

        args, background = parse_command(line)

        if args is None:
            continue

        run_command(args, background)


if __name__ == "__main__":

    if os.name == "nt":
        print("Este programa está pensado para Unix/Linux (usa fork).")
        sys.exit(1)

    main()